### ISSUE TITLE
Shader Toggler repository

### ISSUE THREAD

**Issue by originalnicodr** [framedsc/Sitesource#107]
Since Frans now released the [Shader Toggler](https://github.com/FransBouma/ShaderToggler), there has already been a number of HUD togglers made with it that it would be worth having hosted on the site (they are .inis after all). We might want to wait if Frans wants to keep working on the format of said .inis, but when he thinks they are ready we should have them listed somewhere. What I was thinking of is having something like the [cheat engine archive](https://framedsc.com/cheattablearchive.htm) but in a table format like the [UUU game list](https://framedsc.com/GeneralGuides/universal_ue4_consoleunlocker.htm#games-that-work-with-the-unlocker) in case we want to mention something about the HUD toggler (ex. it also lets you toggle off a grain shader).

While we are at it, it might be a good idea to make a new guide category for `ReShade Addons` guides, that being for this shader toggler repository, a guide on how to make a shader toggler, or, when the addons needed for it get made/fixed, a guide for dumping, upscaling and replacing game textures.

**Comment by FransBouma** [comment]
Was thinking about it indeed, but would wait till after reshade 5.1 has been released (which should be coming friday or so), and when I have my final release ready of the toggler (as the current one is lacking some features). The cheat table archive format is a good idea!

**Comment by originalnicodr** [comment]
Implemented.
