### ISSUE TITLE
Updated Dying Light 2 Toggler

### ISSUE THREAD

**Issue by andrewt1989** [framedsc/Sitesource#112]
[Dying_Light_2.zip](https://github.com/framedsc/Sitesource/files/8483669/Dying_Light_2.zip)

updated Toggler

Caps Lock - Lens flare and screen dirt
F2 - Hides air vents and floaty debris (but also inadvertently hides some other smoke and fire sources)
F3 - Hides Distant Birds
F4 - Hides HUD
F5 - Just floaty debris

**Comment by originalnicodr** [comment]
Updated.
