### ISSUE TITLE
Fix image scaling on Chrome

### ISSUE THREAD

**Issue by moyevka** [framedsc/Sitesource#116]
Downscaled images look significantly worse on Chrome.

Chrome:
![image](https://user-images.githubusercontent.com/89507878/163542681-8a4fe03a-17e7-458d-a0bd-055448b6ec8c.png)

Firefox:
![image](https://user-images.githubusercontent.com/89507878/163542745-5d2694f2-699a-4c3e-847d-2435aff180c8.png)

Probably solvable with [this](https://stackoverflow.com/questions/37906602/blurry-downscaled-images-in-chrome) or an alternative.

**Comment by FransBouma** [comment]
So the `image-rendering: -webkit-optimize-contrast;` addition looks like a good solution. Will see if i can cram that in this morning

**Comment by FransBouma** [comment]
Fixed :)
