### ISSUE TITLE
(universal unreal unlocker 4) steam screenshot key not working

### ISSUE THREAD

**Issue by OBIPPO** [framedsc/Sitesource#162]
trying this with scorn on steam and screenshot keys don't work. tried f12 and f1 to no avail.

is this the correct forum? since there's no dedicated UUU forum, reddit, way to contact, etc...

thx in advance.

**Comment by FransBouma** [comment]
This isn't the right forum, the UUU is available on my patreon (https://patreon.com/Otis_Inf), so feedback is to be given there. That is, v4 which does work with scorn.

That said, the default device for the camera is set to 'both' which blocks both gamepad and kb/mouse for input to the game. If you use a gamepad, set camera device to 'gamepad' in the igcsclient's configuration tab, and kb/mouse then shouldn't be blocked to the game (as it only blocks game devices as input). If you don't have a gamepad, press `Numpad .` to enable input to the game and this will allow F12 to reach the game (and thus steam).

**Comment by OBIPPO** [comment]
TY!
