### ISSUE TITLE
ShaderToggler - HUD - Yakuza Kiwami

### ISSUE THREAD

**Issue by PweSol** [framedsc/Sitesource#174]
Another HUD toggle. This time for the game Yakuza Kiwami. More will come from me, as I'll likely be doing this for every game I play.
```
[General]
AmountGroups=1

[Group0_VertexShaders]
AmountHashes=0

[Group0_PixelShaders]
ShaderHash0=1080760357
ShaderHash1=3326432788
ShaderHash2=3438768936
AmountHashes=3

[Group0]
Name=HUD
ToggleKey=771751936
```
Using the delete button as usual.

**Comment by FransBouma** [comment]
Thanks!

Would it be an idea to provide these as a mergable PR, perhaps? Our shadertogglers are all in separate ini files, and added to a table in <https://github.com/framedsc/Sitesource/blob/master/markdown/ReshadeGuides/Addons/shader_toggler_repository.md>

**Comment by FransBouma** [comment]
I'll add this one for now, but perhaps next time could you create a PR? Thanks!
