### ISSUE TITLE
Re-link to old version?

### ISSUE THREAD

**Issue by apocalyptech** [framedsc/Sitesource#44]
I know it's certainly not considered supported software anymore, but could a link back to the old v1.0.16 version be added back in somewhere?  It looks like the mega.nz link is still available if you happen to know the URL, at least.  I ask because I've been using it on Linux via Wine/Proton to do modding in Borderlands 3, and IGCS Injector plus the old version of the DLL to enable console works great in Wine/Proton, but the newer versions don't seem to work at all.

I know it's very much an edge case, of course.  If you're unwilling to put a link back to the old version anywhere, would it be acceptable for me to at least distribute the old `UniversalUE4UnlockerDumper.dll` somewhere else, with appropriate credits + links back to the current UUU versions?  It'd be easy enough to just grab ICGS Injector from their github.

Thanks!

**Comment by FransBouma** [comment]
Why do you need to 'distribute the dll somewhere else' ? If it's for your own situation, the one you have works, right?

**Comment by apocalyptech** [comment]
Well basically because I know other folks also run BL3 on Linux, and they might want to be able to run the mods too (which requires console access, and this DLL is the only thing I've found which actually enables the console).  When I'm documenting this stuff for the mod community, I can't help but be as helpful as possible to other potential Linux weirdos like myself.  :)

As I say, I totally understand if you don't want it anywhere else; this is after all a strange little corner case.

**Comment by FransBouma** [comment]
Ok, well indeed I don't want the dll to be hosted anywhere else. So I'm sorry but I have to deny your request.

**Comment by apocalyptech** [comment]
Okay, no worries, thanks anyway!
