### ISSUE TITLE
Add the rest of Martys patreon shaders to the shader catalogue

### ISSUE THREAD

**Issue by originalnicodr** [framedsc/Sitesource#94]
Currently, we only have RTGI listed I believe. Would be cool to also have his other patreon shaders so people know about them and can subscribe if they are interested. Here is a list someone wrote with a little description. Might not be complete but its a good place to start:

## Beta:
- qUINTReGrade - colour correction suite, successor to qUINT Lightroom, includes Solaris (bloom shader) & Insight (image analysis tool)
## Alpha:
- qUINTPhysical DoF - fancy dof shader with really nice bokeh highlights 
- qUINTMXAO v2 - compute-based version of MXAO, runs 2-4x faster
- qUINTClarity - image enhancement shader, makes things "clearer" (might be similar to the texture slider in camera raw or lightroom) dunno haven't seen much of it but it's going to be merged into ReGrade soon (so drop to beta)

**Comment by moyevka** [comment]
Physical DoF is now in beta. Alpha has a new shader: MXGI - basically MXAO with added GI, or RTGI without the raytracing. Planned to be merged with MXAO v2 at some point, currently they're separate shaders.

**Comment by originalnicodr** [comment]
Implemented in [93eb009](https://github.com/framedsc/Sitesource/commit/93eb0098ac97cc84692c42e6273884c76d1c38f7).
