### ISSUE TITLE
Unity Explorer guide

### ISSUE THREAD

**Issue by originalnicodr** [framedsc/Sitesource#98]
Write a new guide using [VTVRVXIV's latest freecam](https://www.youtube.com/watch?v=qufWSNPyeYQ). We will probably be able to take quite a few stuff from the current guide. As far as I understand VTV hasn't made a version of the new cam for il2cpp yet, so keep that in mind.

I would still keep the old guide for achievement purposes, especially if VTV hasn't made a cam for il2cpp games yet.

**Comment by FransBouma** [comment]
The guide for VTVRVXIV's tools is still in the repo, but not linked in the json file since commit #a6da217. (by request).

**Comment by moyevka** [comment]
https://github.com/sinai-dev/UnityExplorer

**Comment by originalnicodr** [comment]
Uploaded [VTVRVXIVs UnityExplorer guide](https://framedsc.com/GeneralGuides/universal_unity_freecam.htm). Haven't marked this issue as solved yet because I want to include some things from my previous guide in this one, and expand on some other stuff. Hopefully will be able to do so in the coming days.

**Comment by originalnicodr** [comment]
Forgot to close this after making the new [Cinematic Unity Explorer guide](https://framedsc.com/GeneralGuides/cinematic-unity-explorer.htm).
